name: Publish NuGet package to GitHub registry
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "*.md"
jobs:
  package:
    name: Package and Publish GitHub Package (NuGet)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: DotEnv
        uses: xom9ikk/dotenv@v1.0.2
      - name: Read version from tag
        id: version
        uses: frabert/replace-string-action@v2.0
        with:
          string: ${{ github.ref_name }}
          pattern: 'v'
          replace-with: ''
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore Solution Packages
        run: nuget restore $env:SOLUTION
      - name: Build Solution
        run: msbuild $env:SOLUTION -m
      - name: Create NuGet Package
        run: nuget pack "$WORKSPACE/${env:NUSPEC}" -Version $VERSION -OutputDirectory "$WORKSPACE/Build"
        env:
          VERSION: ${{ steps.version.outputs.replaced }}
          WORKSPACE: ${{ github.repository_workspace }}
      - name: Publish NuGet Package on GitHub
        run: nuget push "$WORKSPACE/Build/*.nupkg" --source "$REPOSITORY/index.json" --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKSPACE: ${{ github.repository_workspace }}
          REPOSITORY: ${{ github.server_url }}/${{ github.repository_owner }}