name: Publish NuGet package to GitHub registry
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "*.md"
jobs:
  package:
    name: Package and Publish GitHub Package (NuGet)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: DotEnv
        uses: xom9ikk/dotenv@v1.0.2
      - name: Read version from tag
        id: version
        uses: frabert/replace-string-action@v2.0
        with:
          string: ${{ github.ref_name }}
          pattern: 'v'
          replace-with: ''
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore Solution Packages
        run: nuget restore $env:SOLUTION
      - name: Build Solution
        run: msbuild $env:SOLUTION -m
      - name: Create NuGet Package
        run: nuget pack "./${env:NUSPEC}" -Version ${env:VERSION} -OutputDirectory ./Build
        env:
          VERSION: ${{ steps.version.outputs.replaced }}
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
      - name: Publish NuGet Package on GitHub
        run: |
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "${env:SERVICE_INDEX}"
          dotnet nuget push "./Build/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVICE_INDEX: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json